### PR TITLE
Login

### PR DESCRIPTION
**Pull request by valerietonsor**

### CODE REVIEW

**Review by emmykg38 — APPROVED** [review]
Looks great!

**Review by krystalwhite — APPROVED** [review]

**Review by krystalwhite — CHANGES_REQUESTED** [review]
Hi. 13/14 of the files look great and I'm really impressed by what everyone has put together! 
May we add error message statements that come up on authentication in the User class and can we delete the extra comments in the text?  (I was uncertain whether those were changes I could do on my own or not.)

**Comment by emmykg38** [comment]
Good eye, Krystal!!
This was on the login branch, but definitely something that should have been handled by registration. I've updated the login branch to include these changes (appropriate error messages for every field, deleted comments). The most recent push comment says "still missing error messages for incompatible passwords" but the error message does in fact exist. Branch should be ready to merge now (pending merge conflicts...)

**Review by krystalwhite — APPROVED** [review]
Thanks for making those changes! Looks great!

**Pull request merged**
