### PR TITLE
Logout

### PR DESCRIPTION
**Pull request by emmykg38**
this is the code from valerie's branch "navbar_logout", which we had difficulty merging last night. Entire application runs with added feature.

### CODE REVIEW

**Comment by krystalwhite** [comment]
All my pages operate with the logout in corner except for one. When I click on a route from the "my saved routes" page, the displayed route page shows login. Also, I see from the code that the user's name should display with a "welcome" message, and that does not render for me.
image
image

**Comment by emmykg38** [comment]
Updated code to display 'Logout' link when viewing a user's single trip, and to display greeting message with username after login

**Review by krystalwhite — APPROVED** [review]
Woohoo, looks great!

**Review by mgunnhawkins — APPROVED** [review]
Looks good!

**Pull request merged**
